#!/bin/bash
set -e

# Удаляем файл sudoers, если он существует
if [ -f /etc/sudoers.d/sqlmanager ]; then
    rm -f /etc/sudoers.d/sqlmanager
fi

# Перезагружаем systemd
systemctl daemon-reload || true

exit 0
