#!/bin/bash
set -e

# Останавливаем и отключаем сервис
systemctl stop sqlmanager.service || true
systemctl disable sqlmanager.service || true

# Удаляем файл sudoers, если он существует
if [ -f /etc/sudoers.d/sqlmanager ]; then
    rm -f /etc/sudoers.d/sqlmanager
fi

exit 0
